SELECT ID,
CASE
WHEN GROUPRANK = 1 THEN 'CRITICAL'
WHEN GROUPRANK = 2 THEN 'HIGH'
WHEN GROUPRANK = 3 THEN 'MEDIUM'
ELSE 'LOW'
END AS COLONY_NAME
FROM (SELECT ID,
NTILE(4) OVER (ORDER BY SIZE_OF_COLONY DESC) AS GROUPRANK
FROM ECOLI_DATA) AS B
ORDER BY ID;