-- 코드를 입력하세요
SELECT TO_CHAR(B.SALES_DATE,'YYYY') AS YEAR, EXTRACT(MONTH FROM B.SALES_DATE) AS MONTH, A.GENDER,
COUNT(DISTINCT A.USER_ID) AS USERS
FROM USER_INFO A, ONLINE_SALE B 
WHERE A.USER_ID=B.USER_ID AND A.GENDER IS NOT NULL
GROUP BY TO_CHAR(B.SALES_DATE,'YYYY'), EXTRACT(MONTH FROM B.SALES_DATE), A.GENDER
ORDER BY TO_CHAR(B.SALES_DATE,'YYYY'), EXTRACT(MONTH FROM B.SALES_DATE), A.GENDER
