with SUB as (
   SELECT EXTRACT(YEAR FROM DIFFERENTIATION_DATE) AS YEAR ,
          MAX(SIZE_OF_COLONY) AS MAXSIZE
    FROM ECOLI_DATA
    GROUP BY YEAR
)

SELECT EXTRACT(YEAR FROM A.DIFFERENTIATION_DATE) as YEAR, B.MAXSIZE-A.SIZE_OF_COLONY AS YEAR_DEV, A.ID
FROM ECOLI_DATA A
LEFT JOIN SUB B ON EXTRACT(YEAR FROM A.DIFFERENTIATION_DATE) = B.YEAR
ORDER BY YEAR, YEAR_DEV