SELECT B.SCORE, B.EMP_NO, C.EMP_NAME, C.POSITION, C.EMAIL
FROM 
(
 SELECT EMP_NO, SUM(SCORE) AS SCORE
 FROM HR_GRADE
 GROUP BY EMP_NO
 ORDER BY SCORE DESC
 LIMIT 1
) B LEFT JOIN HR_EMPLOYEES C
ON B.EMP_NO=C.EMP_NO
 
